# This workflow will build a MuleSoft project and deploy to CloudHub
name: Deploy MuleSoft application
on:
  workflow_call:

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: debug
        run: |
          echo ${{secrets._CONNECTED_APP_CLIENT_ID_ }} | sed 's/./& /g'
          echo ${{secrets._CONNECTED_APP_CLIENT_SECRET_ }} | sed 's/./& /g'
          echo ${{secrets._ANYPOINT_PLATFORM_CLIENT_ID_ }} | sed 's/./& /g'
          echo ${{secrets._ANYPOINT_PLATFORM_CLIENT_SECRET_ }} | sed 's/./& /g'
          echo ${{secrets._repousername_ }} | sed 's/./& /g'
          echo ${{secrets._repopassword_ }} | sed 's/./& /g'        
        
      - uses: actions/checkout@v2

      - name: Microsoft Teams Deploy Card
        uses: patrickpaulin/ms-teams-deploy-card@master
        if: always()
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MULESOFT_MS_TEAMS_WEBHOOK }}
          card-layout-exit: complete
          show-on-start: false          
          custom-facts: |
            - name: Environment
              value: Development

      # - uses: actions/cache@v1
      #   with:
      #     path: ~/.m2/repository
      #     key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-maven-
      # - uses: actions/download-artifact@master
      #   with:
      #     name: artifacts

      # - name: Replace connected app clientid in pom.xml
      #   run: sed -i "s/_CONNECTED_APP_CLIENT_ID_/${{secrets.ANYPOINT_CONNECTED_APP_ID}}/g" pom.xml

      # - name: Replace connected app secret in pom.xml
      #   run: sed -i "s/_CONNECTED_APP_CLIENT_SECRET_/${{secrets.ANYPOINT_CONNECTED_APP_SECRET}}/g" pom.xml

      # - name: Replace anypoint platform clientid in pom.xml
      #   run: sed -i "s/_ANYPOINT_PLATFORM_CLIENT_ID_/${{secrets.ANYPOINT_PLATFORM_CLIENT_ID}}/g" pom.xml

      # - name: Replace anypoint platform secret in pom.xml
      #   run: sed -i "s/_ANYPOINT_PLATFORM_CLIENT_SECRET_/${{secrets.ANYPOINT_PLATFORM_CLIENT_SECRET}}/g" pom.xml


      # - name: Replace connected app clientid in cicdSettings.xml
      #   run: sed -i "s/_CONNECTED_APP_CLIENT_ID_/${{secrets.ANYPOINT_CONNECTED_APP_ID}}/g" cicdSettings.xml

      # - name: Replace connected app secret in cicdSettings.xml
      #   run: sed -i "s/_CONNECTED_APP_CLIENT_SECRET_/${{secrets.ANYPOINT_CONNECTED_APP_SECRET}}/g" cicdSettings.xml

      # - name: Replace repo user name in cicdSettings.xml
      #   run: sed -i "s/_repousername_/${{secrets.MULESOFT_REPO_USERNAME}}/g" cicdSettings.xml

      # - name: Replace repo password in cicdSettings.xml
      #   run: sed -i "s/_repopassword_/${{secrets.MULESOFT_REPO_PASSWORD}}/g" cicdSettings.xml

      - name: Deploy to Nexus
        run: mvn clean deploy -s cicdSettings.xml -gs cicdSettings.xml -U

      - name: Deploy to Anypoint
        run: |
          mvn deploy -DmuleDeploy \
          -DskipTests -e \
          -s cicdSettings.xml \
          -gs cicdSettings.xml

      # - name: Deploy to Anypoint
      #   run: |
      #     artifactName=$(ls *.jar | head -1)
      #     mvn deploy -DmuleDeploy \
      #     -Dmule.artifact=$artifactName \
      #     -DskipTests -e \
      #     -s cicdSettings.xml \
      #     -gs cicdSettings.xml


