name: Deploy mulesoft common services

on:
  workflow_call:
    secrets:
      ANYPOINT_CONNECTED_APP_ID:
        required: true
      ANYPOINT_CONNECTED_APP_SECRET:
        required: true
      ANYPOINT_PLATFORM_CLIENT_ID:
        required: true
      ANYPOINT_PLATFORM_CLIENT_SECRET:
        required: true
      MULESOFT_REPO_USERNAME:
        required: true
      MULESOFT_REPO_PASSWORD:
        required: true
      MULESOFT_MS_TEAMS_WEBHOOK:
        required: true

jobs:
  deploy:
    name: Deploy stack
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check Commit Type
      uses: gsactions/commit-message-checker@v2
      with:
        pattern: '/#minor'
        flags: 'gm'
        error: 'Commit message requires the word #minor'      

    - name: Microsoft Teams Deploy Card
      uses: patrickpaulin/ms-teams-deploy-card@master
      if: always()
      with:
        github-token: ${{ github.token }}
        webhook-uri: ${{ secrets.MULESOFT_MS_TEAMS_WEBHOOK }}
        card-layout-exit: complete
        show-on-start: false
        custom-facts: |
          - name: Environment
            value: Development

    - name: Replace connected app clientid in pom.xml
      run: sed -i "s/ANYPOINT_CONNECTED_APP_ID/${{secrets.ANYPOINT_CONNECTED_APP_ID}}/g" pom.xml

    - name: Replace connected app secret in pom.xml
      run: sed -i 's/ANYPOINT_CONNECTED_APP_SECRET/${{secrets.ANYPOINT_CONNECTED_APP_SECRET}}/g' pom.xml

    - name: Replace anypoint platform clientid in pom.xml
      run: sed -i 's/ANYPOINT_PLATFORM_CLIENT_ID/${{secrets.ANYPOINT_PLATFORM_CLIENT_ID}}/g' pom.xml

    - name: Replace anypoint platform secret in pom.xml
      run: sed -i 's/ANYPOINT_PLATFORM_CLIENT_SECRET/${{secrets.ANYPOINT_PLATFORM_CLIENT_SECRET}}/g' pom.xml


    - name: Replace connected app clientid in cicdSettings.xml
      run: sed -i 's/ANYPOINT_CONNECTED_APP_ID/${{secrets.ANYPOINT_CONNECTED_APP_ID}}/g' cicdSettings.xml

    - name: Replace connected app secret in cicdSettings.xml
      run: sed -i 's/ANYPOINT_CONNECTED_APP_SECRET/${{secrets.ANYPOINT_CONNECTED_APP_SECRET}}/g' cicdSettings.xml

    - name: Replace repo user name in cicdSettings.xml
      run: sed -i 's/MULESOFT_REPO_USERNAME/${{secrets.MULESOFT_REPO_USERNAME}}/g' cicdSettings.xml

    - name: Replace repo password in cicdSettings.xml
      run: sed -i 's/MULESOFT_REPO_PASSWORD/${{secrets.MULESOFT_REPO_PASSWORD}}/g' cicdSettings.xml

#     - name: Deploy to Nexus
#       run: mvn clean deploy -s cicdSettings.xml -gs cicdSettings.xml
